diff example1.got  Outputs > example1.diff
diff example2.got  Outputs > example2.diff
diff example3.got  Outputs > example3.diff
diff example4.got  Outputs > example4.diff
diff example5.got  Outputs > example5.diff
diff example6.got  Outputs > example6.diff
diff example7a.got Outputs > example7a.diff
diff example7b.got Outputs > example7b.diff
diff example8.got  Outputs > example8.diff
diff example9.got  Outputs > example9.diff
diff example10.got Outputs > example10.diff
diff example11.got Outputs > example11.diff
diff example12.got Outputs > example12.diff
diff example13.got Outputs > example13.diff
diff example14.got Outputs > example14.diff
diff example15.got Outputs > example15.diff
diff example16.got Outputs > example16.diff
diff example17.got Outputs > example17.diff
diff example17a.got Outputs > example17a.diff
diff example18.got Outputs > example18.diff
diff example19.got Outputs > example19.diff
diff example20.got Outputs > example20.diff
diff example21.got Outputs > example21.diff
diff example22.got Outputs > example22.diff
diff example23.got Outputs > example23.diff
diff example24.got Outputs > example24.diff
diff example25.got Outputs > example25.diff
diff example26.got Outputs > example26.diff
diff example27.got Outputs > example27.diff
diff example28.got Outputs > example28.diff
diff example29.got Outputs > example29.diff
diff example30.got Outputs > example30.diff
diff example31.got Outputs > example31.diff
diff example32.got Outputs > example32.diff
diff example33.got Outputs > example33.diff
diff example34.got Outputs > example34.diff
diff example35.got Outputs > example35.diff
diff example36.got Outputs > example36.diff
diff example37.got Outputs > example37.diff
diff example38.got Outputs > example38.diff
diff example39.got Outputs > example39.diff
diff example40.got Outputs > example40.diff
diff example41.got Outputs > example41.diff
diff example42.got Outputs > example42.diff
diff example43.got Outputs > example43.diff
diff example44.got Outputs > example44.diff
diff example45.got Outputs > example45.diff
diff example46.got Outputs > example46.diff
diff example47.got Outputs > example47.diff
diff example48.got Outputs > example48.diff
diff example49.got Outputs > example49.diff
diff example50.got Outputs > example50.diff
diff example51.got Outputs > example51.diff
diff example52.got Outputs > example52.diff
diff example53.got Outputs > example53.diff
diff example54.got Outputs > example54.diff
diff example55.got Outputs > example55.diff
diff example56.got Outputs > example56.diff
diff example57.got Outputs > example57.diff
diff example58.got Outputs > example58.diff
diff example59.got Outputs > example59.diff
diff example60.got Outputs > example60.diff
diff example61.got Outputs > example61.diff
diff example62.got Outputs > example62.diff
diff example63.got Outputs > example63.diff
diff example64.got Outputs > example64.diff
diff example65.got Outputs > example65.diff
diff example66.got Outputs > example66.diff
diff example67.got Outputs > example67.diff
diff example68.got Outputs > example68.diff
diff example69.got Outputs > example69.diff
diff example70.got Outputs > example70.diff
diff example71.got Outputs > example71.diff
diff example72.got Outputs > example72.diff
diff example73.got Outputs > example73.diff
diff example74.got Outputs > example74.diff
diff example75.got Outputs > example75.diff
diff example76.got Outputs > example76.diff
